import { ParkingLot, ParkingSlot, Vehicle, Booking, Notification, PricingConfig, User } from '@/types'

export const MOCK_USERS: User[] = [
  {
    id: 'user-customer-1',
    name: 'Arun Kumar',
    email: 'arun@example.com',
    phone: '+91 9876543210',
    role: 'CUSTOMER',
    status: 'active',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&q=80',
    createdAt: '2026-01-15T10:00:00Z',
  },
  {
    id: 'user-admin-1',
    name: 'ParkEase Administrator',
    email: 'admin@parkease.com',
    phone: '+91 9999999999',
    role: 'ADMIN',
    status: 'active',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&q=80',
    createdAt: '2026-01-01T00:00:00Z',
  },
]

export const MOCK_PARKING_LOTS: ParkingLot[] = [
  {
    id: 'lot-1',
    name: 'ParkEase Central Hub',
    address: '100 MG Road, Central Business District',
    area: 'MG Road',
    city: 'Bengaluru',
    description: 'Multi-level premium covered parking lot equipped with EV charging stations and 24/7 surveillance.',
    latitude: 12.9716,
    longitude: 77.5946,
    openingTime: '06:00 AM',
    closingTime: '11:59 PM',
    pricePerHour: 50,
    parkingType: 'Covered',
    amenities: ['CCTV', 'Security', 'EV Charging', 'Covered Parking', 'Valet', 'Accessible Parking'],
    totalSlots: 32,
    availableSlots: 22,
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1506521781263-d8422e82f27a?w=800&q=80',
    status: 'active',
  },
  {
    id: 'lot-2',
    name: 'City Mall Underground Hub',
    address: '45 Forum Avenue, Koramangala',
    area: 'Koramangala',
    city: 'Bengaluru',
    description: 'Spacious basement parking directly connected to retail stores, cinema multiplex, and dining floor.',
    latitude: 12.9352,
    longitude: 77.6245,
    openingTime: '09:00 AM',
    closingTime: '11:00 PM',
    pricePerHour: 40,
    parkingType: 'Basement',
    amenities: ['CCTV', 'Security', 'Covered Parking', 'Accessible Parking'],
    totalSlots: 24,
    availableSlots: 16,
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1590674899484-d5640e854abe?w=800&q=80',
    status: 'active',
  },
  {
    id: 'lot-3',
    name: 'Airport Express Parking Plaza',
    address: 'Terminal 1 Expressway, Devanahalli',
    area: 'Devanahalli',
    city: 'Bengaluru',
    description: 'Long-term secure parking near airport terminal with automated gate barrier and free shuttle bus.',
    latitude: 13.1986,
    longitude: 77.7066,
    openingTime: '12:00 AM',
    closingTime: '11:59 PM',
    pricePerHour: 80,
    parkingType: 'Open',
    amenities: ['CCTV', 'Security', 'EV Charging', 'Valet'],
    totalSlots: 40,
    availableSlots: 28,
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1573348722427-f1d6819fdf98?w=800&q=80',
    status: 'active',
  },
  {
    id: 'lot-4',
    name: 'Tech Park Solar Carpark',
    address: 'Outer Ring Road, ITPL Phase 2',
    area: 'Whitefield',
    city: 'Bengaluru',
    description: 'Eco-friendly tech park parking lot covered with solar canopy panels and high-speed EV chargers.',
    latitude: 12.9854,
    longitude: 77.7285,
    openingTime: '07:00 AM',
    closingTime: '10:00 PM',
    pricePerHour: 45,
    parkingType: 'Covered',
    amenities: ['CCTV', 'Security', 'EV Charging', 'Covered Parking'],
    totalSlots: 30,
    availableSlots: 19,
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1506521781263-d8422e82f27a?w=800&q=80',
    status: 'active',
  },
]

export const MOCK_SLOTS: Record<string, ParkingSlot[]> = {
  'lot-1': [
    { id: 's1', parkingLotId: 'lot-1', slotNumber: 'A01', section: 'A', slotType: 'EV', vehicleType: 'EV', status: 'Available', pricePerHour: 55 },
    { id: 's2', parkingLotId: 'lot-1', slotNumber: 'A02', section: 'A', slotType: 'Accessible', vehicleType: 'Car', status: 'Available', pricePerHour: 50 },
    { id: 's3', parkingLotId: 'lot-1', slotNumber: 'A03', section: 'A', slotType: 'Standard', vehicleType: 'Car', status: 'Occupied', pricePerHour: 50 },
    { id: 's4', parkingLotId: 'lot-1', slotNumber: 'A04', section: 'A', slotType: 'Standard', vehicleType: 'Car', status: 'Available', pricePerHour: 50 },
    { id: 's5', parkingLotId: 'lot-1', slotNumber: 'A05', section: 'A', slotType: 'Standard', vehicleType: 'Bike', status: 'Available', pricePerHour: 25 },
    { id: 's6', parkingLotId: 'lot-1', slotNumber: 'A06', section: 'A', slotType: 'Standard', vehicleType: 'Bike', status: 'Maintenance', pricePerHour: 25 },
    { id: 's7', parkingLotId: 'lot-1', slotNumber: 'B01', section: 'B', slotType: 'VIP', vehicleType: 'SUV', status: 'Available', pricePerHour: 65 },
    { id: 's8', parkingLotId: 'lot-1', slotNumber: 'B02', section: 'B', slotType: 'Standard', vehicleType: 'Car', status: 'Available', pricePerHour: 50 },
    { id: 's9', parkingLotId: 'lot-1', slotNumber: 'B03', section: 'B', slotType: 'Standard', vehicleType: 'Car', status: 'Occupied', pricePerHour: 50 },
    { id: 's10', parkingLotId: 'lot-1', slotNumber: 'B04', section: 'B', slotType: 'Standard', vehicleType: 'Car', status: 'Available', pricePerHour: 50 },
  ],
}

export const MOCK_VEHICLES: Vehicle[] = [
  { id: 'v1', userId: 'user-customer-1', vehicleNumber: 'KA-01-MJ-4321', vehicleType: 'Car', model: 'Honda City', color: 'White', isDefault: true },
  { id: 'v2', userId: 'user-customer-1', vehicleNumber: 'KA-05-EV-9999', vehicleType: 'EV', model: 'Tata Nexon EV', color: 'Teal Blue', isDefault: false },
]

export const MOCK_BOOKINGS: Booking[] = [
  {
    id: 'b1',
    bookingReference: 'PK-2026-000123',
    userId: 'user-customer-1',
    parkingLotId: 'lot-1',
    slotId: 's1',
    vehicleId: 'v1',
    bookingDate: '2026-09-14',
    startTime: '14:00',
    endTime: '16:00',
    durationHours: 2,
    parkingFee: 100,
    serviceFee: 10,
    discount: 0,
    totalAmount: 115,
    status: 'Booked',
    paymentMethod: 'UPI',
    paymentStatus: 'Successful',
    createdAt: '2026-09-14T09:30:00Z',
    parkingLotName: 'ParkEase Central Hub',
    slotNumber: 'A01',
    vehicleNumber: 'KA-01-MJ-4321',
    userName: 'Arun Kumar',
    userEmail: 'arun@example.com',
  },
  {
    id: 'b2',
    bookingReference: 'PK-2026-000098',
    userId: 'user-customer-1',
    parkingLotId: 'lot-2',
    slotId: 's7',
    vehicleId: 'v2',
    bookingDate: '2026-09-10',
    startTime: '11:00',
    endTime: '14:00',
    durationHours: 3,
    parkingFee: 120,
    serviceFee: 10,
    discount: 0,
    totalAmount: 135,
    status: 'Completed',
    paymentMethod: 'Card',
    paymentStatus: 'Successful',
    createdAt: '2026-09-10T10:00:00Z',
    parkingLotName: 'City Mall Underground Hub',
    slotNumber: 'B01',
    vehicleNumber: 'KA-05-EV-9999',
    userName: 'Arun Kumar',
    userEmail: 'arun@example.com',
  },
]

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'n1',
    userId: 'user-customer-1',
    title: 'Booking Confirmed!',
    message: 'Your booking PK-2026-000123 at ParkEase Central Hub for Slot A01 is confirmed.',
    type: 'booking',
    isRead: false,
    createdAt: '2026-09-14T09:30:00Z',
  },
  {
    id: 'n2',
    userId: 'user-customer-1',
    title: 'Parking Reminder',
    message: 'Your parking slot A01 booking starts today at 02:00 PM.',
    type: 'reminder',
    isRead: true,
    createdAt: '2026-09-14T08:00:00Z',
  },
]

export const MOCK_PRICING: PricingConfig = {
  baseHourlyRate: 50,
  weekendMultiplier: 1.2,
  peakHourMultiplier: 1.5,
  serviceFee: 10,
  vehicleRates: {
    Car: 1.0,
    Bike: 0.5,
    SUV: 1.3,
    EV: 1.1,
  },
}
